import "../globals.css";
import { Inter } from "next/font/google";
import AuthCheck from "@/common/AuthCheck";
import AdminNavBar from "@/components/Navbars/Admin/AdminNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Delicie Restorante",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const styles = {
    scrollBehavior: "smooth",
  };
  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <body className={`${inter.className} bg-gray-50`}>
        <AuthCheck />
        <AdminNavBar />
        {children}
      </body>
    </html>
  );
}
