import Image from "next/image";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Navbar from "@/common/Navbar";
import Footer from "@/common/Footer";
import { ReactQueryProvider } from "./ReactQueryProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Delicie Restorante",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const styles = {
    scrollBehavior: "smooth",
  };
  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <body className={inter.className}>
        <ReactQueryProvider>
          <Toaster />
          <Navbar />
          {children}
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
